### ISSUE TITLE
Please add My Approval Status for each PR

### ISSUE THREAD

**Issue by simonua** [mbukosky/slack-bot-vsts-pullrequests#1]
Mike,

It would be helpful to know what "my" approval status is for a PR. I'm thinking specifically from a Visual Studio Team Services perspective as I am less familiar with other Git and GitHub PR implementations.

Having this information will help me understand whether I need to take action. If I already approved, it's less likely that I need to be back in the PR than a "Waiting for Author", for example.

Thank you!

**Comment by mbukosky** [comment]
I started looking into this, it is not going to be easy. I need to try and find the information in vsts rest api.

**Comment by simonua** [comment]
The changes look great, Mike! Thank you very much!
