### ISSUE TITLE
Please Indicate My vs. Other PRs

### ISSUE THREAD

**Issue by simonua** [mbukosky/slack-bot-vsts-pullrequests#2]
Mike,

It would be helpful to have a distinction in the list between PRs I submitted vs. ones I am mentioned on.  

This would help me prioritize what I may pay attention to.

Thank you,

Simon

**Comment by mbukosky** [comment]
This is complete, can you please let me know if you agree with the layout

**Comment by simonua** [comment]
The new layout is terrific! Thank you! The order of my vs. others, then by created date is spot on. Thanks, Mike!
