### ISSUE TITLE
PR Still Shows in List After Completed

### ISSUE THREAD

**Issue by simonua** [mbukosky/slack-bot-vsts-pullrequests#9]
I have a PR that I created that remains in my PR list. I completed the PR yesterday; however, I have no response on the PR. 

Maybe it still shows in the list because I have not issued a response? I would expect PRs that get completed or abandoned would drop out of my listing.

**Comment by mbukosky** [comment]
Looking into it now

**Comment by mbukosky** [comment]
Would me be possible to give me an example? I am having a hard time replicating the issue.

**Comment by mbukosky** [comment]
NM I found the issue

**Comment by simonua** [comment]
Awesome. I should be able to test it quickly if you create a fix. Thank you!

**Comment by mbukosky** [comment]
@simonua give it a try, code deployed

**Comment by simonua** [comment]
@mbukosky, I can confirm this is fixed. Thank you very much!
